# otel config file
receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:55681
        cors:
          allowed_origins:
            - https://*.force.com

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: promexample
    const_labels:
      label1: value1
  logging:

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:

extensions:
  pprof:
  pprof/1:
    endpoint: "0.0.0.0:1888"
    block_profile_fraction: 3
    mutex_profile_fraction: 5
  zpages:
    endpoint: :55679

service:
  extensions: [pprof/1, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
      
